"""Add BlockedUser table

Revision ID: 9dcf75d8bf98
Revises: 1e7e99e08747
Create Date: 2025-04-14 10:57:16.802143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dcf75d8bf98'
down_revision = '1e7e99e08747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_id', sa.Integer(), nullable=True),
    sa.Column('blocked_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blocked_user')
    # ### end Alembic commands ###
